name: Bug report
description: Report a bug in vivy-fluorite-app
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: desc
    attributes:
      label: What happened?
      description: Describe the issue clearly.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: "OS, Browser, Node version"
